spring.application.name=musicplayer
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=BlueGa
server.port=${SERVER_PORT:8080}

aws.s3.bucket=bluega-audio
aws.s3.accessKey=${AWS_ACCESS_KEY}
aws.s3.secretKey=${AWS_SECRET_KEY}
aws.s3.region=ap-southeast-3

# Maximum file size per upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB